---

- name: Install unzip
  apt: name=unzip state=present

- name: Is IK installed
  stat: path={{ elasticsearch_home_dir }}/plugins/ik/elasticsearch-analysis-ik-{{ elasticsearch_ik_version }}.jar
  register: plugin_ik

- name: Download IK plugin
  get_url:
    url={{ elasticsearch_ik_url }}
    dest=/tmp/ik.{{ elasticsearch_ik_version }}.zip
  when: not plugin_ik.stat.exists

- name: Clean IK directory
  file: path={{ elasticsearch_home_dir }}/plugins/ik state=absent
  when: not plugin_ik.stat.exists

- name: Ensure IK directory
  file: path={{ elasticsearch_home_dir }}/plugins/ik state=directory
  when: not plugin_ik.stat.exists

- name: Extract IK plugin
  unarchive: src=/tmp/ik.{{ elasticsearch_ik_version }}.zip dest={{ elasticsearch_home_dir }}/plugins/ik copy=no
  when: not plugin_ik.stat.exists
