---

- include: install.deb.yml
  when: ansible_os_family == 'Debian'
  tags: [elasticsearch, install]

- include: plugin.yml
  tags: [elasticsearch, install]

- include: ik.yml
  tags: [elasticsearch, install]
  when: elasticsearch_ik_enabled

- include: config.deb.yml
  when: ansible_os_family == 'Debian'
  tags: [elasticsearch, config]
