---

- include: install.deb.yml
  when: ansible_os_family == 'Debian'
  tags: [elasticsearch, install]

- include: config.deb.yml
  when: ansible_os_family == 'Debian'
  tags: [elasticsearch, config]
